### ISSUE TITLE
Breaks with multiple outputs

### ISSUE THREAD

**Issue by NaridaL** [TrySound/rollup-plugin-terser#5] opened 2018-09-16 16:13 UTC
rollup.config.js
```js
import { terser } from 'rollup-plugin-terser'

export default {
	input: "index.js",
	output: [
		{
			format: "umd",
			file: "index.umd.min.js",
			name: "index",
		},
		{
			format: "es",
			file: "index.module.min.js",
		},
	],
	plugins: [
		terser(),
	],
}
```

index.js
```js
export const FOO = 2
```

versions
```json
{
    "rollup": "^0.66.0",
    "rollup-plugin-terser": "^3.0.0",
    "terser": "^3.8.2"
}
```

```
PS C:\Users\aval\tsdev\rpterser> npm run rollup

> rpterser@1.0.0 rollup C:\Users\aval\tsdev\rpterser
> rollup -c
Output
index.js → index.umd.min.js, index.module.min.js...
[!] (terser plugin) Error: Farm is ended, no more calls can be done to it
Error: Farm is ended, no more calls can be done to it
    at exports.default.end (C:\Users\aval\tsdev\rpterser\node_modules\jest-worker\build\index.js:166:13)
    at Object.generateBundle (C:\Users\aval\tsdev\rpterser\node_modules\rollup-plugin-terser\index.js:38:19)
    at C:\Users\aval\tsdev\rpterser\node_modules\rollup\dist\rollup.js:20850:25
    at process._tickCallback (internal/process/next_tick.js:68:7)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rpterser@1.0.0 rollup: `rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rpterser@1.0.0 rollup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aval\AppData\Roaming\npm-cache\_logs\2018-09-16T16_09_11_939Z-debug.log
```

Expected output: should work

Commenting out either output config prevents errors.

**Comment by TrySound** [comment] 2018-09-16 16:28
Could you try to use multiple configs instead of multiple outputs? Like this
```js
import { terser } from 'rollup-plugin-terser'

export default [
  {
    input: "index.js",
    output: {
      format: "umd",
      file: "index.umd.min.js",
      name: "index",
    },
    plugins: [ terser() ],
  },
  {
    input: "index.js",
    output: {
      format: "es",
      file: "index.module.min.js",
    },
    plugins: [ terser() ],
  }
]
```

**Comment by jhoffmcd** [comment] 2018-09-18 04:39
Confirmed, the issue is surfacing for me with a multiple output config as well.

**Comment by motss** [comment] 2018-09-29 11:03
Facing the same issue after new release of Rollup

**Comment by Ziv-Barber** [comment] 2018-10-05 19:31
Same here.

**Comment by berkaey** [comment] 2018-10-10 09:13
same here too.

**Comment by visormatt** [comment] 2018-10-17 18:57
Thanks for the suggestion @TrySound. Unfortunately we're using it in a `monorepo` which would be a bit more work to update and we'd prefer to hold off until its supported as its simply IMO a cleaner approach

**Comment by visormatt** [comment] 2018-10-17 18:58
> @visormatt Multiple configs instead of multiple outputs also work.

Thanks for the suggestion @TrySound. Unfortunately we're using it in a `monorepo` which would be a bit more work to update and we'd prefer to hold off until its supported as its simply IMO a cleaner approach

**Comment by janriemer** [comment] 2018-11-24 15:29
I've made [a PR](https://github.com/TrySound/rollup-plugin-terser/pull/16) that should fix this. :wink:

**Comment by lucifer1004** [comment] 2018-11-27 03:49
Mark here to get notifications when this issue is fixed.

**Comment by kopax** [comment] 2018-12-16 13:34
Any update on this? I have the same error

**Comment by TrySound** [comment] 2018-12-16 13:39
@kopax I'm gonna merge https://github.com/TrySound/rollup-plugin-terser/pull/19 soon. Currently I recommend to use multiconfig or v1 instead.

**Comment by kopax** [comment] 2018-12-16 13:47
@TrySound thanks for your explanation.

Do you mean v1 of terser plugin ?

I've fixed by using multiconfig: 

```js

// this was commented
// if (prod) plugins.push(uglify(), visualizer({ filename: './bundle-stats.html' }));
// if (prod) plugins.push(terser(), visualizer({ filename: './bundle-stats.html' }));

export default [{
  input: 'src/index.js',
  external,
  output: output.filter((o) => o.format !== 'es'),
// does not work ?
//  plugins: prod ? plugins.concat([uglify(), visualizer({ filename: './bundle-stats.html' })]) : plugins,
  plugins,
}, {
  input: 'src/index.js',
  external,
  output: output.filter((o) => o.format === 'es'),
  plugins: prod ? plugins.concat([terser(), visualizer({ filename: './bundle-stats.html' })]) : plugins,
}];
```

I am able to build but as you can see, I have lost the uglify step except for the es module.

I have tried to used both plugin uglify and terser, this give me the error: 
```
src/index.js → dist/@bootstrap-styled/color.min.js, dist/@bootstrap-styled/color.cjs.min.js...
[!] (uglify plugin) Error: Farm is ended, no more calls can be done to it
Error: Farm is ended, no more calls can be done to it
    at exports.default.end (/home/dka/workspace/github.com/bootstrap-styled/color/node_modules/rollup-plugin-uglify/node_modules/jest-worker/build/index.js:166:13)
    at Object.generateBundle (/home/dka/workspace/github.com/bootstrap-styled/color/node_modules/rollup-plugin-uglify/index.js:38:19)
    at /home/dka/workspace/github.com/bootstrap-styled/color/node_modules/rollup/dist/rollup.js:21948:25
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

```

Do you also have a solution for that ?

**Comment by kopax** [comment] 2018-12-16 13:48
Nevermind, I have found that uglify plugin also need to be called once per instance.

**Comment by luyzh** [comment] 2018-12-18 06:15
I have the same error 😢

**Closed** 2019-01-01 21:06 UTC

**Comment by kopax** [comment] 2019-01-02 18:21
Is this fixed?

**Comment by TrySound** [comment] 2019-01-02 18:41
@kopax Yep. Should be fixed in v4

**Comment by visormatt** [comment] 2019-01-04 00:47
No changes were required in our configuration other than bumping the version. Great work and thanks for the wonderful package @TrySound and contributors 🙇
